### ISSUE TITLE
calculate_rrs based on cell_type and condition

### ISSUE THREAD

**Issue by rosanababu** [FloWuenne/scFunctions#16]
Hi

Thanks for this wonderful tool.. Is there any option to calculate RSS based on cell_type and condition to visualise cell_type specific RSS activity for each condition side by side in heatmap?

I'm currently using below code, but shows Error: Your input vector stores NA values...
rrs_df <- calculate_rrs(cellInfo,
              binary_regulons = binary_regulons_trans,
              cell_type_column = c("cell_type", "Conditions"))

Please suggest whether I should run pySCENIC grn, ctx, aucell steps by subsetting each conditions separately to calculate_rrs and visualising in heat map for each conditions?

Many thanks,
Rosana

**Comment by FloWuenne** [comment]
Hi @rosana08 ,

Thanks for the kind words. It's really just some of my personal code I put online to help people run similar analysis as me.

Nowadays, my favourite way of running SCENIC is actually via the nextflow pipelines they wrote, either [SCENICprotocol](https://github.com/aertslab/SCENICprotocol) or [VSN pipelines](https://github.com/vib-singlecell-nf/vsn-pipelines). 

They do have some code to utilize the resulting SCOPE object in python downstream and get RSS scores as well:
https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.ipynb

Regarding the error from my code, I do think that this is due to NA values existing in your rss data frame. Could you share a subset of the data or the summary of your input data so that I could help more directly please?
