### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by GildasLepennetier** [FloWuenne/scFunctions#4]
Hi Florian

In the example "complete pipeline", there is a little problem with the dataset: the default value for the calculate_rrs function will not be found, and no value is actually set.
Just modify the [markdown file](https://github.com/FloWuenne/scFunctions/blob/master/Tutorials/process_SCENIC.md):

```
rrs_df <- calculate_rrs(metadata_sub, 
   binary_regulons = binary_regulons_trans, 
   cell_type_column = "cell_type")
```

I would actually remove the default in the function itself.

[Otherwise, I think this is so far nice work, thanks](https://media.makeameme.org/created/nice-work-jcoc2i.jpg)

EDIT: I actually created a pull request.

**Comment by FloWuenne** [comment]
Thanks so much for the pull requests, Gildas! I have merged them to the main branch just now! 

I will have to update the tutorial and add another tutorial for processing data from the new [SCENICprotocol repo](https://github.com/aertslab/SCENICprotocol) since the output is in a different format. I will do this once I find some time next week! Glad to know my functions helped!
